strange panic backtrace
Here's the back trace:

    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
    stack backtrace:
       0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
                 at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
       1: std::sys_common::backtrace::_print
                 at src/libstd/sys_common/backtrace.rs:70
       2: std::panicking::default_hook::{{closure}}
                 at src/libstd/sys_common/backtrace.rs:58
                 at src/libstd/panicking.rs:200
       3: std::panicking::default_hook
                 at src/libstd/panicking.rs:215
       4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
                 at src/libstd/panicking.rs:478
       5: std::panicking::continue_panic_fmt
                 at src/libstd/panicking.rs:385
       6: std::panicking::try::do_call
                 at src/libstd/panicking.rs:312
       7: <T as core::any::Any>::type_id
                 at src/libcore/panicking.rs:85
       8: <T as core::any::Any>::type_id
                 at src/libcore/panicking.rs:49
       9: <chrono::naive::time::NaiveTime as core::cmp::PartialOrd>::partial_cmp
                 at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/macros.rs:11
      10: manta_mreq::TimelineEvent::relative_start
                 at src/lib.rs:319
      11: alloc::raw_vec::alloc_guard
                 at src/lib.rs:120
      12: mreq::main
                 at src/bin/mreq.rs:32
      13: std::rt::lang_start::{{closure}}
                 at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
      14: std::panicking::try::do_call
                 at src/libstd/rt.rs:49
                 at src/libstd/panicking.rs:297
      15: panic_unwind::dwarf::eh::read_encoded_pointer
                 at src/libpanic_unwind/lib.rs:87
      16: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
                 at src/libstd/panicking.rs:276
                 at src/libstd/panic.rs:388
                 at src/libstd/rt.rs:48
      17: std::rt::lang_start
                 at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/rt.rs:64
      18: mreq::fatal

This is on OS X with Rust 1.34.1.

The root problem here is that in frame 10, `relative_start()` invokes
`unwrap()` on a `None` value.  The caller (in frame 11) was supposed to
have invoked another function first that would have made this call
valid.

But I'm still new to Rust and I'm using this as a chance to better
understand the stack trace itself.  I had a few issues trying to
interpret it:

- There's an extra frame "mreq::fatal" on the bottom of the stack --
  that makes no sense to me.  I don't believe that function was ever
  invoked.  (I can reproduce a similar issue in a small test program.)
- At frame 12, main() actually invokes `mri_dump()`, but that's not on
  the stack at all.  I think it actually is there, as frame 11, but it's
  reported as "alloc::raw_vec::alloc_guard".  I say that because
  "src/lib.rs:120" within my project is inside `mri_dump()`, and it's the
  point where we invoke `relative_start()`.
- The file paths that are inside my module look just like the paths
  inside Rust itself.  When I read this I skipped frame 11 (which is
  actually where the problem is) because it looked like an
  internal-to-Rust frame to me.
- It was a little confusing to me that "panic" appears both above and
  below main() on the stack.  Is that because under RUST_BACKTRACE the
  runtime goes through a different code path before invoking main()?
- There's no unwrap() on the stack at all.  I guess it's inlined?  Is
  there any way to more clearly point to the frame that called unwrap()
  on a None?